name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Oppgave 1 test
      id: oppgave-1-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Oppgave 1 test
        setup-command: ''
        command: gradle test --tests Oppgave1Test
        timeout: 10
        max-score: 1
    - name: Oppgave 2 test
      id: oppgave-2-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Oppgave 2 test
        setup-command: ''
        command: gradle test --tests Oppgave2Test
        timeout: 10
        max-score: 1
    - name: Oppgave 3 test
      id: oppgave-3-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Oppgave 3 test
        setup-command: ''
        command: gradle test --tests Oppgave3Test
        timeout: 10
        max-score: 1
    - name: Oppgave 4 test
      id: oppgave-4-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Oppgave 4 test
        setup-command: ''
        command: gradle test --tests Oppgave4Test
        timeout: 10
        max-score: 1
    - name: Oppgave 5 test
      id: oppgave-5-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Oppgave 5 test
        setup-command: ''
        command: gradle test --tests Oppgave5Test
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        OPPGAVE-1-TEST_RESULTS: "${{steps.oppgave-1-test.outputs.result}}"
        OPPGAVE-2-TEST_RESULTS: "${{steps.oppgave-2-test.outputs.result}}"
        OPPGAVE-3-TEST_RESULTS: "${{steps.oppgave-3-test.outputs.result}}"
        OPPGAVE-4-TEST_RESULTS: "${{steps.oppgave-4-test.outputs.result}}"
        OPPGAVE-5-TEST_RESULTS: "${{steps.oppgave-5-test.outputs.result}}"
      with:
        runners: oppgave-1-test,oppgave-2-test,oppgave-3-test,oppgave-4-test,oppgave-5-test
